apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -proxy
resources:
- ../../base

patchesStrategicMerge:
- _deploy.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: traefik
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--providers.kubernetesingress.labelselector=app=traefik-proxy"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--entrypoints.web.proxyprotocol.insecure=true"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--entrypoints.websecure.proxyprotocol.insecure=true"
images:
- name: traefik
  newName: traefik
  newTag: "2.3"
