apiVersion: v1
kind: Service
metadata:
  name: traefik-no-proxy
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: traefik-no-proxy
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443
